// DO NOT EDIT, file is generated by the prepare-react-samples gulp task
import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom';
import { Chart, Series, Title, XAxis, YAxis, Tooltip } from '@highcharts/react';
import { Accessibility } from '@highcharts/react/options/Accessibility';
// External Redux libraries via esm.sh
import { Provider, useSelector, useDispatch } from 'https://esm.sh/react-redux@9.1.0?external=react';
import { configureStore, createSlice } from 'https://esm.sh/@reduxjs/toolkit@2.2.1?external=react';
// --- 1. Redux Logic ---
const chartSlice = createSlice({
    name: 'chart',
    initialState: {
        points: [
            15,
            12,
            18,
            22,
            30,
            25,
            19,
            24,
            28,
            32
        ]
    },
    reducers: {
        randomize: (state)=>{
            state.points = state.points.map(()=>Math.floor(Math.random() * 40));
        },
        tick: (state)=>{
            const lastPoint = state.points[state.points.length - 1];
            const nextPoint = Math.max(0, Math.min(50, lastPoint + (Math.random() - 0.5) * 10));
            // Immutable update for reactivity
            state.points = [
                ...state.points.slice(1),
                Number(nextPoint.toFixed(2))
            ];
        }
    }
});
const { randomize, tick } = chartSlice.actions;
const store = configureStore({
    reducer: {
        chart: chartSlice.reducer
    }
});
// --- 2. Component Logic ---
function ChartComponent() {
    const points = useSelector((state)=>state.chart.points);
    const dispatch = useDispatch();
    const [isLive, setIsLive] = useState(false);
    useEffect(()=>{
        let interval;
        if (isLive) {
            interval = setInterval(()=>{
                dispatch(tick());
            }, 500);
        }
        return ()=>clearInterval(interval);
    }, [
        isLive,
        dispatch
    ]);
    return /*#__PURE__*/ React.createElement("div", {
        id: "demo-container"
    }, /*#__PURE__*/ React.createElement(Chart, null, /*#__PURE__*/ React.createElement(Title, null, "Advanced Reactive Redux Dashboard"), /*#__PURE__*/ React.createElement(Accessibility, null), /*#__PURE__*/ React.createElement(Tooltip, {
        shared: true
    }), /*#__PURE__*/ React.createElement(XAxis, {
        categories: [
            'T-9',
            'T-8',
            'T-7',
            'T-6',
            'T-5',
            'T-4',
            'T-3',
            'T-2',
            'T-1',
            'Now'
        ]
    }), /*#__PURE__*/ React.createElement(YAxis, {
        title: {
            text: 'Metric Value'
        },
        min: 0,
        max: 60
    }), /*#__PURE__*/ React.createElement(Series, {
        type: "areaspline",
        name: "Live Stream",
        data: points,
        color: "#2c3e50",
        fillColor: {
            linearGradient: {
                x1: 0,
                y1: 0,
                x2: 0,
                y2: 1
            },
            stops: [
                [
                    0,
                    'rgba(44, 62, 80, 0.5)'
                ],
                [
                    1,
                    'rgba(44, 62, 80, 0)'
                ]
            ]
        }
    })), /*#__PURE__*/ React.createElement("div", {
        className: "button-wrapper"
    }, /*#__PURE__*/ React.createElement("button", {
        className: "btn btn-manual",
        onClick: ()=>dispatch(randomize()),
        disabled: isLive
    }, "Manual Randomize"), /*#__PURE__*/ React.createElement("button", {
        className: `btn ${isLive ? 'btn-stop' : 'btn-start'}`,
        onClick: ()=>setIsLive(!isLive)
    }, isLive ? 'Stop Live Feed' : 'Start Live Feed')), /*#__PURE__*/ React.createElement("div", {
        className: "demo-info-box"
    }, /*#__PURE__*/ React.createElement("strong", null, "Redux + Highcharts React v4.2:"), /*#__PURE__*/ React.createElement("ul", null, /*#__PURE__*/ React.createElement("li", null, "The global store manages the ", /*#__PURE__*/ React.createElement("code", null, "points"), " array."), /*#__PURE__*/ React.createElement("li", null, "React hooks (", /*#__PURE__*/ React.createElement("code", null, "useSelector"), ") provide a reactive subscription."), /*#__PURE__*/ React.createElement("li", null, "The chart updates via props, ensuring high-performance re-rendering."))));
}
// --- 3. Rendering ---
ReactDOM.createRoot(document.querySelector('#container'))?.render(/*#__PURE__*/ React.createElement(Provider, {
    store: store
}, /*#__PURE__*/ React.createElement(ChartComponent, null)));
