/*
 * Copyright (C) Highsoft AS
 */

const gulp = require('gulp');
const log = require('../libs/log');

function treeToMappingRecursive(key, branch, keyPath, mapping = {}) {
    if (branch.children) {
        keyPath.push(key);
        Object.entries(branch.children).forEach(([subkey, child]) => {
            treeToMappingRecursive(subkey, child, keyPath, mapping);
        });
        keyPath.pop();
    }
    if (branch.doclet && branch.doclet.requires) {
        const fullKey = (keyPath.filter(Boolean).join('.') + '.' + key)
            .replace(/^\./u, '');
        mapping[
            fullKey
        ] = branch.doclet.requires.map(r => r.replace(/module:/u, ''));
    }
    return mapping;
}

/**
 * Create the DependencyMapping module file
 *
 * @return {Promise<void>}
 *         Promise to keep
 */
async function dependencyMapping() {
    const fs = require('fs').promises,
        path = require('path');

    const mapping = {};

    for (const product of ['highcharts', 'highstock', 'highmaps', 'gantt']) {
        const treeJsonPath = path.join(
                __dirname,
                `../../build/api/${product}/tree.json`
            ),
            treeJson = await fs.readFile(treeJsonPath, 'utf8'),
            tree = JSON.parse(treeJson);

        log.message(`Reading ${treeJsonPath} ...`);

        const productSpecificMapping = treeToMappingRecursive(
            void 0,
            { children: tree },
            []
        );

        Object.assign(mapping, productSpecificMapping);
    }

    // Remove plotOptions.* entries, and combine them with series.* entries
    let seriesMismatch = false;
    Object.keys(mapping).forEach(key => {
        if (key.startsWith('plotOptions.')) {
            const seriesType = key.replace('plotOptions.', 'series.');
            if (
                /^series\.[a-zA-Z]+$/u.test(seriesType) &&
                mapping[key].join(',') !== mapping[seriesType]?.join(',')
            ) {
                log.warn(
                    `Mismatched dependencies for ${key} and ${seriesType}:\n` +
                    ` ${mapping[key]} vs ${mapping[seriesType]}`
                );
                seriesMismatch = true;
            }
            delete mapping[key];
        }
    });
    if (seriesMismatch) {
        throw new Error(
            'Mismatched dependencies between plotOptions and series types'
        );
    }

    // Rename key series.series to plotOptions.series
    const deepSeriesRegex = /^series\.[a-zA-Z]+\./u;
    Object.entries(mapping).forEach(([key, value]) => {
        if (deepSeriesRegex.test(key)) {
            mapping[
                key.replace(deepSeriesRegex, 'plotOptions.series.')
            ] = value;
            delete mapping[key];
        }
    });

    // Remove all `lang.*` entries, as these are not features per se
    Object.keys(mapping).forEach(key => {
        if (key.startsWith('lang.')) {
            delete mapping[key];
        }
    });

    // Remove unnecessary definitions at lower levels. For example if both
    // `exporting` and `exporting.buttons` are defined, remove the latter.
    Object.entries(mapping).forEach(([key, value]) => {
        const parentKey = key.split('.').slice(0, -1).join('.');
        if (
            mapping[parentKey] &&
            mapping[parentKey].toString() === value.toString()
        ) {
            delete mapping[key];
        }
    });

    // Sort the object by key name
    const sortedMapping = {};
    Object.keys(mapping).sort().forEach(key => {
        sortedMapping[key] = mapping[key];
    });

    const mappingString = JSON
        .stringify(sortedMapping, null, 4)
        .replace(/"/gu, '\'');

    await fs.writeFile(
        path.join(
            __dirname,
            '../../ts/Extensions/Autoload/DependencyMapping.ts'
        ),
        `/**
 * Dependencies for the autoload feature.
 *
 * DO NOT EDIT THIS FILE. This file is generated using the
 * 'gulp dependency-mapping' task.
 */
const DependencyMapping: Record<string, Array<string>> = ${mappingString};
export default DependencyMapping;
`,
        'utf8'
    );
    log.success(
        'Wrote references to ts/Extensions/Autoload/DependencyMapping.ts'
    );

}

require('./jsdoc');

const buildTreeJS = true;
gulp.task(
    'dependency-mapping',
    buildTreeJS ?
        gulp.series('jsdoc', dependencyMapping) :
        dependencyMapping
);
