/*
 * Copyright (C) Highsoft AS
 */

const gulp = require('gulp');
const fs = require('fs');
const path = require('path').posix;
const log = require('../libs/log');

/* *
 *
 *  Constants
 *
 * */

const BASE_FORM_ICONS = ['edit', 'destroy', 'close'];
const DEFAULT_VIEWBOX = 32;
const FILL_COLOR = '#4B4B4D';
const ICONS_DIR = '../../gfx/stock-icons';

const CONFIG_NAMES = {
    stockTools: {
        prefix: 'stockToolsIconPrefix',
        fillColor: 'fillColor',
        outPath: '../../ts/Stock/StockTools/StockToolsIcons.ts',
        message: 'Wrote SVG icons to ts/Stock/StockTools/StockToolsIcons.ts'
    },
    baseForm: {
        prefix: 'baseFormIconPrefix',
        fillColor: 'baseIconFillColor',
        outPath: '../../ts/Shared/BaseFormIcons.ts',
        message: 'Wrote SVG icons to ts/Shared/BaseFormIcons.ts'
    }
};

/**
 *
 *  Functions
 *
 */

/**
 * Extract the viewBox value from an SVG string.
 *
 * @param {string} svg
 *                 The SVG string.
 *
 * @return {number}
 *          The viewBox value.
 */
function extractViewBox(svg) {
    const m = svg.match(/<svg\b[^>]*\bviewBox\s*=\s*"([^"]+)"/iu);
    if (!m || !m[1]) {
        return DEFAULT_VIEWBOX;
    }
    const last = m[1].trim().split(/\s+/u).pop();
    return Number(last) ?? DEFAULT_VIEWBOX;
}

/**
 * Helper function to write icon files with appropriate naming.
 *
 * @param {string} iconString
 *                 The combined string with icons definitions.
 * @param {string} type
 *                 The type of icons: 'stockTools' or 'baseForm'.
 *
 * @return {void}
 */
function writeIconsFile(iconString, type) {
    const config = CONFIG_NAMES[type];

    fs.writeFileSync(
        path.join(__dirname, config.outPath),
        `/* *
 *
 *  (c) 2026 Highsoft AS
 *  Authors:
 *  - Paweł Fus
 *  - Jedrzej Ruta
 *
 *  License: www.highcharts.com/license
 *
 *  DO NOT EDIT THIS FILE! This file is created by 'gulp scripts-icons' task.
 *
 * */

'use strict';
// Auto-generated SVG JSON
/* eslint-disable max-len */

/**
 * Helper function to generate SVG icon prefix with given viewBox size.
 * @internal
 */
const ${config.prefix} = (viewBox: number): string =>
    \`<?xml version="1.0" encoding="utf-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 \${viewBox} \${viewBox}">\`;

/**
 * Constants
 */
const ${config.fillColor} = '${FILL_COLOR}';

export default {
${iconString}
};\n`,
        'utf8'
    );
    log.success(config.message);
}

/**
 * Helper function to sanitize SVG content. **Note:** The `<style>` tag
 * is not optimized here, it should be done in source SVG file instead.
 *
 * @param {string} input
 *                The raw SVG string.
 *
 * @return {string}
 *         Sanitized SVG string.
 */
function sanitizeIcon(input) {
    let previous;
    let sanitized = input;

    do {
        previous = sanitized;
        sanitized = sanitized
            .replace(/^\uFEFF/u, '') // UTF-8 BOM
            .replace(/<\?xml[\s\S]*?\?>\s*/iu, '') // <?xml ... ?>
            .replace(/<!DOCTYPE[\s\S]*?>\s*/iu, '') // <!DOCTYPE ...>
            .replace(/<!--[\s\S]*?(?:--!?>|$)/gu, '') // all comments
            .replace(/<!--/gu, '') // remove any remaining <!--
            .replace(/--!?>/gu, '') // remove any remaining --> or --!>
            .replace(/<svg\b[^>]*>\s*(\r?\n)?/iu, '') // <svg> tag & whitespace
            .replace(/\s+id="[^"]*"/giu, '') // id attributes
            .replace(/\t/gu, '    ') // replace tabs with spaces
            .replace(/\s+"/gu, '"') // remove whitespace before closing tags
            // replaces fill color with variable
            .replace(/fill="#4B4B4D"/giu, 'fill="${fillColor}"');
    } while (sanitized !== previous);

    return sanitized;
}

/**
 * Create the stock icons module file based on SVG files in gfx/stock-icons
 *
 * @return {Promise<void>}
 *         Promise to keep
 */
async function scriptsIcons() {
    const iconsDir = path.join(__dirname, ICONS_DIR);

    const svgIcons = fs.readdirSync(iconsDir)
        .filter(file => file.toLowerCase().endsWith('.svg'))
        .map(file => path.join(iconsDir, file));

    let stockToolsIconString = '';
    let baseFormIconString = '';

    for (const icon of svgIcons) {
        const rawIcon = fs.readFileSync(icon, 'utf8');
        const iconName = path.basename(icon, '.svg');
        const viewBox = extractViewBox(rawIcon);

        // Cleanup SVG icon content in a loop until sanitized
        let processedIcon = rawIcon;
        let previousIcon;
        do {
            previousIcon = processedIcon;
            processedIcon = sanitizeIcon(processedIcon);
        } while (processedIcon !== previousIcon);


        // Categorize icons into stock tools and base form
        if (BASE_FORM_ICONS.includes(iconName)) {
            const baseFormIcon = processedIcon
                .replace(/\$\{fillColor\}/gu, '${baseIconFillColor}');
            baseFormIconString +=
                `    '${iconName}.svg': \`` +
                `\${baseFormIconPrefix(${viewBox})}${baseFormIcon}` +
                '`,\n';
        }

        stockToolsIconString +=
            `    '${iconName}.svg': \`` +
            `\${stockToolsIconPrefix(${viewBox})}${processedIcon}` +
            '`,\n';
    }

    // Remove trailing comma/newline from each icon string
    stockToolsIconString = stockToolsIconString.replace(/,\n$/u, '');
    baseFormIconString = baseFormIconString.replace(/,\n$/u, '');

    // Write both icon files
    writeIconsFile(stockToolsIconString, 'stockTools');
    writeIconsFile(baseFormIconString, 'baseForm');
}

gulp.task('scripts-icons', scriptsIcons);
