/**
 * Palette for Highcharts. Do not edit this file! This file is generated using
 * the 'gulp palette' task. Palette colors are defined in highcharts.scss.
 */
const palette = {
    colors: [
        '#7cb5ec',
        '#434348',
        '#90ed7d',
        '#f7a35c',
        '#8085e9',
        '#f15c80',
        '#e4d354',
        '#2b908f',
        '#f45b5b',
        '#91e8e1'
    ],
    backgroundColor: '#ffffff',
    neutralColor100: '#000000',
    neutralColor80: '#333333',
    neutralColor60: '#666666',
    neutralColor40: '#999999',
    neutralColor20: '#cccccc',
    neutralColor10: '#e6e6e6',
    neutralColor5: '#f2f2f2',
    neutralColor3: '#f7f7f7',
    highlightColor100: '#003399',
    highlightColor80: '#335cad',
    highlightColor60: '#6685c2',
    highlightColor20: '#ccd6eb',
    highlightColor10: '#e6ebf5',
    indicatorPositiveLine: '#06b535',
    indicatorNegativeLine: '#f21313'
};
export default palette;
