/* eslint comma-dangle: 0, max-len: 0 */
/**
 * Palette for Highcharts. Palette colors are defined in highcharts.css.
 * **Do not edit this file!** This file is generated using the 'gulp palette'
 * task.
 * @internal
 */

import type PaletteOptions from './PaletteOptions';

/**
 * The palette object specifies colors for the charts and how to apply them.
 *
 * @sample       highcharts/palette/general
 *               General palette options
 * @type         {*}
 * @since        13.0.0
 * @optionparent palette
 */
const palette: PaletteOptions = {
    /**
     * Palette options for light mode.
     */
    light: {
        /**
         * Chart background, point stroke for markers and columns etc
         * @type {Highcharts.ColorType}
         */
        backgroundColor: '#ffffff',
        /**
         * Strong text.
         * @type {Highcharts.ColorType}
         */
        neutralColor100: '#000000',
        /**
         * Main text, axis labels and some strokes.
         * @type {Highcharts.ColorType}
         */
        neutralColor80: '#333333',
        /**
         * Axis title, connector fallback.
         * @type {Highcharts.ColorType}
         */
        neutralColor60: '#666666',
        /**
         * Credits text, export menu stroke.
         * @type {Highcharts.ColorType}
         */
        neutralColor40: '#999999',
        /**
         * Disabled texts, button strokes, crosshair etc.
         * @type {Highcharts.ColorType}
         */
        neutralColor20: '#cccccc',
        /**
         * Grid lines etc.
         * @type {Highcharts.ColorType}
         */
        neutralColor10: '#e6e6e6',
        /**
         * Minor grid lines etc.
         * @type {Highcharts.ColorType}
         */
        neutralColor5: '#f2f2f2',
        /**
         * Tooltip background, button fills, map null points.
         * @type {Highcharts.ColorType}
         */
        neutralColor3: '#f7f7f7',
        /**
         * Drilldown clickable labels, color axis max color.
         * @type {Highcharts.ColorType}
         */
        highlightColor100: '#0022ff',
        /**
         * Selection marker, menu hover, button hover, chart border, navigator series.
         * @type {Highcharts.ColorType}
         */
        highlightColor80: '#334eff',
        /**
         * Navigator mask fill.
         * @type {Highcharts.ColorType}
         */
        highlightColor60: '#667aff',
        /**
         * Ticks and axis line.
         * @type {Highcharts.ColorType}
         */
        highlightColor20: '#ccd3ff',
        /**
         * Pressed button, color axis min color.
         * @type {Highcharts.ColorType}
         */
        highlightColor10: '#e6e9ff',
        /**
         * Indicators
         * @type {Highcharts.ColorType}
         */
        positiveColor: '#06b535',
        /**
         * Indicators
         * @type {Highcharts.ColorType}
         */
        negativeColor: '#f21313',

        /**
         * Colors for data series and points
         * @type {Array<Highcharts.ColorType>}
         */
        colors: [
            '#2caffe',
            '#544fc5',
            '#00e272',
            '#fe6a35',
            '#6b8abc',
            '#d568fb',
            '#2ee0ca',
            '#fa4b42',
            '#feb56a',
            '#91e8e1'
        ]
    }
};
export default palette;
