/* eslint comma-dangle: 0, max-len: 0 */
import type ColorString from './ColorString';
/**
 * Palette for Highcharts. Palette colors are defined in highcharts.scss.
 * **Do not edit this file!** This file is generated using the 'gulp palette' task.
 */
export const enum Palette {
    /**
     * Chart background, point stroke for markers and columns etc
     */
    backgroundColor = '#ffffff',
    /**
     * Strong text.
     */
    neutralColor100 = '#20202C',
    /**
     * Main text and some strokes.
     */
    neutralColor80 = '#3C3C4B',
    /**
     * Axis labels, axis title, connector fallback.
     */
    neutralColor60 = '#77779C',
    /**
     * Credits text, export menu stroke.
     */
    neutralColor40 = '#AAAABF',
    /**
     * Disabled texts, button strokes, crosshair etc.
     */
    neutralColor20 = '#D9D9E2',
    /**
     * Grid lines etc.
     */
    neutralColor10 = '#E7E7EC',
    /**
     * Minor grid lines etc.
     */
    neutralColor5 = '#F2F2F5',
    /**
     * Tooltip backgroud, button fills, map null points.
     */
    neutralColor3 = '#FAFAFB',
    /**
     * Drilldown clickable labels, color axis max color.
     */
    highlightColor100 = '#20202C',
    /**
     * Selection marker, menu hover, button hover, chart border, navigator series.
     */
    highlightColor80 = '#4CAFFE',
    /**
     * Navigator mask fill.
     */
    highlightColor60 = '#0B84E4',
    /**
     * ?.
     */
    highlightColor40 = '#C4C7DE',
    /**
     * Ticks and axis line.
     */
    highlightColor20 = '#B7DFFF',
    /**
     * Pressed button, color axis min color.
     */
    highlightColor10 = '#DBEFFF',
    /**
     * Positive indicator color
     */
    positiveColor = '#06b535',
    /**
     * Negative indicator color
     */
    negativeColor = '#f21313',
}
/**
 * Series palettes for Highcharts. Series colors are defined in highcharts.scss.
 * **Do not edit this file!** This file is generated using the 'gulp palette' task.
 */
const SeriesPalettes = {
    /**
     * Colors for data series and points.
     */
    colors: [
        '#4CAFFE',
        '#5352BE',
        '#FF8D64',
        '#43D376',
        '#708AB9',
        '#C771F3',
        '#6CDDCA',
        '#DD437F',
        '#FAB776',
        '#404E89'
    ] as Array<ColorString>,
};
export default SeriesPalettes;
