/* eslint comma-dangle: 0, max-len: 0 */
/**
 * Palette for Highcharts. Palette colors are defined in highcharts.css.
 * **Do not edit this file!** This file is generated using the 'gulp palette'
 * task.
 * @internal
 */

import type PaletteOptions from './PaletteOptions';

/**
 * The palette object specifies colors for the charts and how to apply them.
 *
 * @sample       highcharts/palette/general
 *               General palette options
 * @type         {*}
 * @since        13.0.0
 * @optionparent palette
 */
const palette: PaletteOptions = {
    /**
     * Palette options for dark mode.
     *
     * @extends palette.light
     */
    dark: {
        backgroundColor: '#141414',
        neutralColor: '#ffffff',
        highlightColor: '#2caffe'
    },
    /**
     * Palette options for light mode.
     */
    light: {
        /**
         * Chart background, point stroke for markers and columns etc
         * @type {Highcharts.ColorType}
         */
        backgroundColor: '#ffffff',
        /**
         * Strong text.
         * @type {Highcharts.ColorType}
         */
        neutralColor: '#000000',
        /**
         * Drilldown clickable labels, color axis max color.
         * @type {Highcharts.ColorType}
         */
        highlightColor: '#0022ff',
        /**
         * Indicators
         * @type {Highcharts.ColorType}
         */
        positiveColor: '#06b535',
        /**
         * Indicators
         * @type {Highcharts.ColorType}
         */
        negativeColor: '#f21313',

        /**
         * Colors for data series and points
         * @type {Array<Highcharts.ColorType>}
         */
        colors: [
            '#2caffe',
            '#544fc5',
            '#00e272',
            '#fe6a35',
            '#6b8abc',
            '#d568fb',
            '#2ee0ca',
            '#fa4b42',
            '#feb56a',
            '#91e8e1'
        ]
    }
};
export default palette;
