// DO NOT EDIT, file is generated by the prepare-react-samples gulp task
import React from 'react';
import ReactDOM from 'react-dom';
import { Chart, Title } from '@highcharts/react';
import { Accessibility } from '@highcharts/react/options/Accessibility';
import { VennSeries } from '@highcharts/react/series/Venn';
export default function ChartComponent() {
    const vennData = [
        {
            sets: [
                'Product A'
            ],
            value: 2,
            name: 'Product A'
        },
        {
            sets: [
                'Product B'
            ],
            value: 2,
            name: 'Product B'
        },
        {
            sets: [
                'Product A',
                'Product B'
            ],
            value: 1,
            name: 'A ∩ B'
        }
    ];
    return /*#__PURE__*/ React.createElement("div", null, /*#__PURE__*/ React.createElement(Chart, null, /*#__PURE__*/ React.createElement(Title, null, "Simple Venn Diagram"), /*#__PURE__*/ React.createElement(Accessibility, null), /*#__PURE__*/ React.createElement(VennSeries, {
        options: {
            name: 'Products'
        },
        data: vennData
    })));
}
ReactDOM.createRoot(document.querySelector('#container'))?.render(/*#__PURE__*/ React.createElement(ChartComponent, null));
