// DO NOT EDIT, file is generated by the prepare-react-samples gulp task
import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import { Chart, Series, Title, XAxis } from '@highcharts/react';
function CountrySelect({ currentCountry, countryData, onChange }) {
    return /*#__PURE__*/ React.createElement("div", null, /*#__PURE__*/ React.createElement("h2", null, "Select country"), Object.keys(countryData).map((countryName)=>/*#__PURE__*/ React.createElement("label", {
            key: countryName
        }, /*#__PURE__*/ React.createElement("input", {
            type: "radio",
            name: "country",
            value: countryName,
            checked: currentCountry === countryName,
            onChange: ()=>onChange(countryName)
        }), countryName)));
}
function TitleFormat({ country }) {
    return /*#__PURE__*/ React.createElement(React.Fragment, null, "Fruit consumption in ", /*#__PURE__*/ React.createElement("em", null, country));
}
function ChartComponent() {
    const countryData = {
        Norway: [
            [
                'Apples',
                1
            ],
            [
                'Pears',
                2
            ],
            [
                'Bananas',
                3
            ],
            [
                'Oranges',
                4
            ]
        ],
        Sweden: [
            [
                'Apples',
                2
            ],
            [
                'Pears',
                1
            ],
            [
                'Bananas',
                5
            ],
            [
                'Oranges',
                1
            ]
        ]
    };
    const [country, setCountry] = useState(Object.keys(countryData)[0]);
    return /*#__PURE__*/ React.createElement("div", null, /*#__PURE__*/ React.createElement(Chart, null, /*#__PURE__*/ React.createElement(Title, null, /*#__PURE__*/ React.createElement(TitleFormat, {
        country: country
    })), /*#__PURE__*/ React.createElement(XAxis, {
        type: "category"
    }), /*#__PURE__*/ React.createElement(Series, {
        type: "column",
        data: countryData[country]
    })), /*#__PURE__*/ React.createElement(CountrySelect, {
        currentCountry: country,
        countryData: countryData,
        onChange: (c)=>setCountry(c)
    }));
}
ReactDOM.createRoot(document.querySelector('#container'))?.render(/*#__PURE__*/ React.createElement(ChartComponent, null));
