/**
 * Dependencies for the autoload feature.
 *
 * DO NOT EDIT THIS FILE. This file is generated using the
 * 'gulp dependency-mapping' task.
 */
const DependencyMapping: Record<string, Array<string>> = {
    'accessibility': [
        'modules/accessibility'
    ],
    'annotations.labelOptions.accessibility': [
        'modules/accessibility'
    ],
    'annotations.labelOptions.includeInDataExport': [
        'modules/export-data'
    ],
    'annotations.labels.point': [
        'modules/annotations'
    ],
    'annotations.shapes.point': [
        'modules/annotations'
    ],
    'annotations': [
        'modules/annotations'
    ],
    'boost': [
        'modules/boost'
    ],
    'chart.displayErrors': [
        'modules/debugger'
    ],
    'chart.events.afterPrint': [
        'modules/exporting'
    ],
    'chart.events.beforePrint': [
        'modules/exporting'
    ],
    'chart.events.drilldown': [
        'modules/drilldown'
    ],
    'chart.events.drillup': [
        'modules/drilldown'
    ],
    'chart.events.drillupall': [
        'modules/drilldown'
    ],
    'chart.events.exportData': [
        'modules/export-data'
    ],
    'chart.events.fullscreenClose': [
        'modules/full-screen'
    ],
    'chart.events.fullscreenOpen': [
        'modules/full-screen'
    ],
    'chart.options3d': [
        'highcharts-3d'
    ],
    'chart.parallelAxes': [
        'modules/parallel-coordinates'
    ],
    'chart.parallelCoordinates': [
        'modules/parallel-coordinates'
    ],
    'chart.polar': [
        'highcharts-more'
    ],
    'chart.zoomKey': [
        'modules/draggable-points'
    ],
    'chart.zooming.key': [
        'modules/draggable-points'
    ],
    'chart.zooming.mouseWheel': [
        'modules/mouse-wheel-zoom'
    ],
    'data': [
        'modules/data'
    ],
    'drilldown': [
        'modules/drilldown'
    ],
    'exporting.accessibility': [
        'modules/accessibility'
    ],
    'exporting.csv.annotations.itemDelimiter': [
        'modules/annotations'
    ],
    'exporting.csv.annotations.join': [
        'modules/annotations'
    ],
    'exporting.csv.annotations': [
        'modules/export-data',
        'modules/annotations'
    ],
    'exporting.csv': [
        'modules/export-data'
    ],
    'exporting.error': [
        'modules/exporting',
        'modules/offline-exporting'
    ],
    'exporting.fallbackToExportServer': [
        'modules/exporting',
        'modules/offline-exporting'
    ],
    'exporting.pdfFont': [
        'modules/offline-exporting'
    ],
    'exporting.showExportInProgress': [
        'modules/export-data'
    ],
    'exporting.showTable': [
        'modules/export-data'
    ],
    'exporting.tableCaption': [
        'modules/export-data'
    ],
    'exporting.useMultiLevelHeaders': [
        'modules/export-data'
    ],
    'exporting.useRowspanHeaders': [
        'modules/export-data'
    ],
    'exporting': [
        'modules/exporting'
    ],
    'lang.contextButtonTitle': [
        'modules/exporting'
    ],
    'lang.downloadCSV': [
        'modules/export-data'
    ],
    'lang.downloadJPEG': [
        'modules/exporting'
    ],
    'lang.downloadMIDI': [
        'modules/sonification'
    ],
    'lang.downloadPDF': [
        'modules/exporting'
    ],
    'lang.downloadPNG': [
        'modules/exporting'
    ],
    'lang.downloadSVG': [
        'modules/exporting'
    ],
    'lang.downloadXLS': [
        'modules/export-data'
    ],
    'lang.drillUpText': [
        'modules/drilldown'
    ],
    'lang.exportData': [
        'modules/export-data'
    ],
    'lang.exportInProgress': [
        'modules/export-data'
    ],
    'lang.hideData': [
        'modules/export-data'
    ],
    'lang.noData': [
        'modules/no-data-to-display'
    ],
    'lang.playAsSound': [
        'modules/sonification'
    ],
    'lang.printChart': [
        'modules/exporting'
    ],
    'lang.viewData': [
        'modules/export-data'
    ],
    'legend.accessibility': [
        'modules/accessibility'
    ],
    'legend.bubbleLegend': [
        'highcharts-more'
    ],
    'navigation.annotationsOptions': [
        'modules/annotations'
    ],
    'navigation.bindings': [
        'modules/annotations'
    ],
    'navigation': [
        'modules/exporting'
    ],
    'navigator.accessibility': [
        'modules/accessibility'
    ],
    'noData': [
        'modules/no-data-to-display'
    ],
    'pane': [
        'highcharts-more'
    ],
    'plotOptions.abands': [
        'indicators/indicators',
        'indicators/acceleration-bands'
    ],
    'plotOptions.ad': [
        'indicators/indicators',
        'indicators/accumulation-distribution'
    ],
    'plotOptions.ao': [
        'indicators/indicators',
        'indicators/ao'
    ],
    'plotOptions.apo': [
        'indicators/indicators',
        'indicators/apo'
    ],
    'plotOptions.arcdiagram': [
        'modules/arc-diagram'
    ],
    'plotOptions.arearange.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'plotOptions.arearange.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'plotOptions.arearange': [
        'highcharts-more'
    ],
    'plotOptions.areasplinerange': [
        'highcharts-more'
    ],
    'plotOptions.aroon': [
        'indicators/indicators',
        'indicators/aroon'
    ],
    'plotOptions.aroonoscillator': [
        'indicators/indicators',
        'indicators/aroon',
        'indicators/aroon-oscillator'
    ],
    'plotOptions.atr': [
        'indicators/indicators',
        'indicators/atr'
    ],
    'plotOptions.bb': [
        'indicators/indicators',
        'indicators/bollinger-bands'
    ],
    'plotOptions.bellcurve': [
        'modules/histogram-bellcurve'
    ],
    'plotOptions.boxplot.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'plotOptions.boxplot.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'plotOptions.boxplot.dragDrop.draggableQ1': [
        'modules/draggable-points'
    ],
    'plotOptions.boxplot.dragDrop.draggableQ3': [
        'modules/draggable-points'
    ],
    'plotOptions.boxplot': [
        'highcharts-more'
    ],
    'plotOptions.bubble': [
        'highcharts-more'
    ],
    'plotOptions.bullet.dragDrop.draggableTarget': [
        'modules/draggable-points'
    ],
    'plotOptions.bullet': [
        'modules/bullet'
    ],
    'plotOptions.cci': [
        'indicators/indicators',
        'indicators/cci'
    ],
    'plotOptions.chaikin': [
        'indicators/indicators',
        'indicators/chaikin'
    ],
    'plotOptions.cmf': [
        'indicators/indicators',
        'indicators/cmf'
    ],
    'plotOptions.cmo': [
        'indicators/indicators',
        'indicators/cmo'
    ],
    'plotOptions.column.depth': [
        'highcharts-3d'
    ],
    'plotOptions.column.edgeColor': [
        'highcharts-3d'
    ],
    'plotOptions.column.edgeWidth': [
        'highcharts-3d'
    ],
    'plotOptions.column.groupZPadding': [
        'highcharts-3d'
    ],
    'plotOptions.columnpyramid': [
        'highcharts-more'
    ],
    'plotOptions.columnrange.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'plotOptions.columnrange.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'plotOptions.columnrange': [
        'highcharts-more'
    ],
    'plotOptions.cylinder': [
        'modules/cylinder'
    ],
    'plotOptions.dema': [
        'indicators/indicators',
        'indicators/dema'
    ],
    'plotOptions.dependencywheel': [
        'modules/dependency-wheel'
    ],
    'plotOptions.disparityindex': [
        'indicators/indicators',
        'indicators/disparity-index'
    ],
    'plotOptions.dmi': [
        'indicators/indicators',
        'indicators/dmi'
    ],
    'plotOptions.dpo': [
        'indicators/indicators',
        'indicators/dpo'
    ],
    'plotOptions.ema': [
        'indicators/indicators'
    ],
    'plotOptions.errorbar': [
        'highcharts-more'
    ],
    'plotOptions.flowmap': [
        'modules/flowmap'
    ],
    'plotOptions.funnel': [
        'modules/funnel'
    ],
    'plotOptions.funnel3d': [
        'highcharts-3d',
        'modules/cylinder',
        'modules/funnel3d'
    ],
    'plotOptions.gantt.dragDrop.draggableEnd': [
        'modules/draggable-points'
    ],
    'plotOptions.gantt.dragDrop.draggableStart': [
        'modules/draggable-points'
    ],
    'plotOptions.gantt': [
        'highcharts-gantt'
    ],
    'plotOptions.gauge': [
        'highcharts-more'
    ],
    'plotOptions.geoheatmap': [
        'modules/geoheatmap'
    ],
    'plotOptions.heikinashi': [
        'modules/heikinashi'
    ],
    'plotOptions.histogram': [
        'modules/histogram-bellcurve'
    ],
    'plotOptions.hollowcandlestick': [
        'modules/hollowcandlestick'
    ],
    'plotOptions.ikh': [
        'indicators/indicators',
        'indicators/ichimoku-kinko-hyo'
    ],
    'plotOptions.item': [
        'modules/item-series'
    ],
    'plotOptions.keltnerchannels': [
        'indicators/indicators',
        'indicators/keltner-channels'
    ],
    'plotOptions.klinger': [
        'indicators/indicators',
        'indicators/klinger'
    ],
    'plotOptions.linearregression': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'plotOptions.linearregressionangle': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'plotOptions.linearregressionintercept': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'plotOptions.linearregressionslope': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'plotOptions.macd': [
        'indicators/indicators',
        'indicators/macd'
    ],
    'plotOptions.mfi': [
        'indicators/indicators',
        'indicators/mfi'
    ],
    'plotOptions.momentum': [
        'indicators/indicators',
        'indicators/momentum'
    ],
    'plotOptions.natr': [
        'indicators/indicators',
        'indicators/natr'
    ],
    'plotOptions.networkgraph': [
        'modules/networkgraph'
    ],
    'plotOptions.obv': [
        'indicators/indicators',
        'indicators/obv'
    ],
    'plotOptions.ohlc.dragDrop.draggableClose': [
        'modules/draggable-points'
    ],
    'plotOptions.ohlc.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'plotOptions.ohlc.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'plotOptions.ohlc.dragDrop.draggableOpen': [
        'modules/draggable-points'
    ],
    'plotOptions.organization': [
        'modules/organization'
    ],
    'plotOptions.packedbubble': [
        'highcharts-more'
    ],
    'plotOptions.pareto': [
        'modules/pareto'
    ],
    'plotOptions.pc': [
        'indicators/indicators',
        'indicators/price-channel'
    ],
    'plotOptions.pictorial': [
        'modules/pictorial'
    ],
    'plotOptions.pie.depth': [
        'highcharts-3d'
    ],
    'plotOptions.pivotpoints': [
        'indicators/indicators',
        'indicators/pivot-points'
    ],
    'plotOptions.polygon': [
        'highcharts-more'
    ],
    'plotOptions.ppo': [
        'indicators/indicators',
        'indicators/ppo'
    ],
    'plotOptions.priceenvelopes': [
        'indicators/indicators',
        'indicators/price-envelopes'
    ],
    'plotOptions.psar': [
        'indicators/indicators',
        'indicators/psar'
    ],
    'plotOptions.pyramid': [
        'modules/funnel'
    ],
    'plotOptions.pyramid3d': [
        'highcharts-3d',
        'modules/cylinder',
        'modules/funnel3d',
        'modules/pyramid3d'
    ],
    'plotOptions.roc': [
        'indicators/indicators',
        'indicators/roc'
    ],
    'plotOptions.rsi': [
        'indicators/indicators',
        'indicators/rsi'
    ],
    'plotOptions.sankey': [
        'modules/sankey'
    ],
    'plotOptions.scatter3d': [
        'highcharts-3d'
    ],
    'plotOptions.series.accessibility': [
        'modules/accessibility'
    ],
    'plotOptions.series.boostBlending': [
        'modules/boost'
    ],
    'plotOptions.series.boostThreshold': [
        'modules/boost'
    ],
    'plotOptions.series.dataGrouping': [
        'modules/stock'
    ],
    'plotOptions.series.description': [
        'modules/accessibility'
    ],
    'plotOptions.series.dragDrop': [
        'modules/draggable-points'
    ],
    'plotOptions.series.gapSize': [
        'modules/broken-axis'
    ],
    'plotOptions.series.gapUnit': [
        'modules/broken-axis'
    ],
    'plotOptions.series.includeInDataExport': [
        'modules/export-data'
    ],
    'plotOptions.series.label': [
        'modules/series-label'
    ],
    'plotOptions.series.lastPrice': [
        'modules/price-indicator'
    ],
    'plotOptions.series.lastVisiblePrice': [
        'modules/price-indicator'
    ],
    'plotOptions.series.onPoint': [
        'modules/series-on-point'
    ],
    'plotOptions.series.point.events.drag': [
        'modules/draggable-points'
    ],
    'plotOptions.series.point.events.dragStart': [
        'modules/draggable-points'
    ],
    'plotOptions.series.point.events.drop': [
        'modules/draggable-points'
    ],
    'plotOptions.series.sonification': [
        'modules/sonification'
    ],
    'plotOptions.slowstochastic': [
        'indicators/indicators',
        'indicators/stochastic',
        'indicators/slow-stochastic'
    ],
    'plotOptions.sma': [
        'indicators/indicators'
    ],
    'plotOptions.solidgauge': [
        'modules/solid-gauge'
    ],
    'plotOptions.stochastic': [
        'indicators/indicators',
        'indicators/stochastic'
    ],
    'plotOptions.streamgraph': [
        'modules/streamgraph'
    ],
    'plotOptions.sunburst': [
        'modules/sunburst'
    ],
    'plotOptions.supertrend': [
        'indicators/indicators',
        'indicators/supertrend'
    ],
    'plotOptions.tema': [
        'indicators/indicators',
        'indicators/tema'
    ],
    'plotOptions.tilemap': [
        'modules/tilemap'
    ],
    'plotOptions.timeline': [
        'modules/timeline'
    ],
    'plotOptions.treegraph': [
        'modules/treemap',
        'modules/treegraph'
    ],
    'plotOptions.treemap': [
        'modules/treemap'
    ],
    'plotOptions.trendline': [
        'indicators/indicators',
        'indicators/trendline'
    ],
    'plotOptions.trix': [
        'indicators/indicators',
        'indicators/tema',
        'indicators/trix'
    ],
    'plotOptions.variablepie': [
        'modules/variable-pie'
    ],
    'plotOptions.variwide': [
        'modules/variwide'
    ],
    'plotOptions.vbp': [
        'indicators/indicators',
        'indicators/volume-by-price'
    ],
    'plotOptions.vector': [
        'modules/vector'
    ],
    'plotOptions.venn': [
        'modules/venn'
    ],
    'plotOptions.vwap': [
        'indicators/indicators',
        'indicators/vwap'
    ],
    'plotOptions.waterfall': [
        'highcharts-more'
    ],
    'plotOptions.williamsr': [
        'indicators/indicators',
        'indicators/williams-r'
    ],
    'plotOptions.windbarb': [
        'modules/windbarb'
    ],
    'plotOptions.wma': [
        'indicators/indicators',
        'indicators/wma'
    ],
    'plotOptions.wordcloud': [
        'modules/wordcloud'
    ],
    'plotOptions.xrange.dragDrop.draggableX1': [
        'modules/draggable-points'
    ],
    'plotOptions.xrange.dragDrop.draggableX2': [
        'modules/draggable-points'
    ],
    'plotOptions.xrange': [
        'modules/xrange'
    ],
    'plotOptions.zigzag': [
        'indicators/indicators',
        'indicators/zigzag'
    ],
    'series.abands': [
        'indicators/indicators',
        'indicators/acceleration-bands'
    ],
    'series.ad': [
        'indicators/indicators',
        'indicators/accumulation-distribution'
    ],
    'series.ao': [
        'indicators/indicators',
        'indicators/ao'
    ],
    'series.apo': [
        'indicators/indicators',
        'indicators/apo'
    ],
    'series.arcdiagram': [
        'modules/sankey',
        'modules/arc-diagram'
    ],
    'series.arearange': [
        'highcharts-more'
    ],
    'series.areasplinerange': [
        'highcharts-more'
    ],
    'series.aroon': [
        'indicators/indicators',
        'indicators/aroon'
    ],
    'series.aroonoscillator': [
        'indicators/indicators',
        'indicators/aroon',
        'indicators/aroon-oscillator'
    ],
    'series.atr': [
        'indicators/indicators',
        'indicators/atr'
    ],
    'series.bb': [
        'indicators/indicators',
        'indicators/bollinger-bands'
    ],
    'series.bellcurve': [
        'modules/histogram-bellcurve'
    ],
    'series.boxplot': [
        'highcharts-more'
    ],
    'series.bubble': [
        'highcharts-more'
    ],
    'series.bullet': [
        'modules/bullet'
    ],
    'series.cci': [
        'indicators/indicators',
        'indicators/cci'
    ],
    'series.chaikin': [
        'indicators/indicators',
        'indicators/chaikin'
    ],
    'series.cmf': [
        'indicators/indicators',
        'indicators/cmf'
    ],
    'series.cmo': [
        'indicators/indicators',
        'indicators/cmo'
    ],
    'series.columnpyramid': [
        'highcharts-more'
    ],
    'series.columnrange': [
        'highcharts-more'
    ],
    'series.cylinder': [
        'modules/cylinder'
    ],
    'series.dema': [
        'indicators/indicators',
        'indicators/dema'
    ],
    'series.dependencywheel': [
        'modules/sankey',
        'modules/dependency-wheel'
    ],
    'series.disparityindex': [
        'indicators/indicators',
        'indicators/disparity-index'
    ],
    'series.dmi': [
        'indicators/indicators',
        'indicators/dmi'
    ],
    'series.dpo': [
        'indicators/indicators',
        'indicators/dpo'
    ],
    'series.dumbbell': [
        'highcharts-more',
        'modules/dumbbell'
    ],
    'series.ema': [
        'indicators/indicators'
    ],
    'series.errorbar': [
        'highcharts-more'
    ],
    'series.funnel': [
        'modules/funnel'
    ],
    'series.funnel3d': [
        'highcharts-3d',
        'modules/cylinder',
        'modules/funnel3d'
    ],
    'series.gantt': [
        'highcharts-gantt'
    ],
    'series.gauge': [
        'highcharts-more'
    ],
    'series.heikinashi': [
        'modules/heikinashi'
    ],
    'series.histogram': [
        'modules/histogram-bellcurve'
    ],
    'series.ikh': [
        'indicators/indicators',
        'indicators/ichimoku-kinko-hyo'
    ],
    'series.item': [
        'modules/item-series'
    ],
    'series.keltnerchannels': [
        'indicators/indicators',
        'indicators/keltner-channels'
    ],
    'series.klinger': [
        'indicators/indicators',
        'indicators/klinger'
    ],
    'series.line.data.description': [
        'modules/accessibility'
    ],
    'series.line.data.dragDrop': [
        'modules/draggable-points'
    ],
    'series.line.data.drilldown': [
        'modules/drilldown'
    ],
    'series.linearregression': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'series.linearregressionangle': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'series.linearregressionintercept': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'series.linearregressionslope': [
        'indicators/indicators',
        'indicators/regressions'
    ],
    'series.lollipop': [
        'highcharts-more',
        'modules/dumbbell',
        'modules/lollipop'
    ],
    'series.macd': [
        'indicators/indicators',
        'indicators/macd'
    ],
    'series.mfi': [
        'indicators/indicators',
        'indicators/mfi'
    ],
    'series.momentum': [
        'indicators/indicators',
        'indicators/momentum'
    ],
    'series.natr': [
        'indicators/indicators',
        'indicators/atr',
        'indicators/natr'
    ],
    'series.networkgraph': [
        'modules/networkgraph'
    ],
    'series.obv': [
        'indicators/indicators',
        'indicators/obv'
    ],
    'series.organization': [
        'modules/sankey',
        'modules/organization'
    ],
    'series.packedbubble': [
        'highcharts-more'
    ],
    'series.pareto': [
        'modules/pareto'
    ],
    'series.pc': [
        'indicators/indicators',
        'indicators/price-channel'
    ],
    'series.pictorial': [
        'modules/pictorial'
    ],
    'series.pivotpoints': [
        'indicators/indicators',
        'indicators/pivot-points'
    ],
    'series.polygon': [
        'highcharts-more'
    ],
    'series.ppo': [
        'indicators/indicators',
        'indicators/ppo'
    ],
    'series.priceenvelopes': [
        'indicators/indicators',
        'indicators/price-envelopes'
    ],
    'series.psar': [
        'indicators/indicators',
        'indicators/psar'
    ],
    'series.pyramid': [
        'modules/funnel'
    ],
    'series.pyramid3d': [
        'modules/pyramid3d'
    ],
    'series.roc': [
        'indicators/indicators',
        'indicators/roc'
    ],
    'series.rsi': [
        'indicators/indicators',
        'indicators/rsi'
    ],
    'series.sankey': [
        'modules/sankey'
    ],
    'series.scatter3d': [
        'highcharts-3d'
    ],
    'series.slowstochastic': [
        'indicators/indicators',
        'indicators/stochastic',
        'indicators/slow-stochastic'
    ],
    'series.sma': [
        'indicators/indicators'
    ],
    'series.solidgauge': [
        'modules/solid-gauge'
    ],
    'series.stochastic': [
        'indicators/indicators',
        'indicators/stochastic'
    ],
    'series.streamgraph': [
        'modules/streamgraph'
    ],
    'series.sunburst': [
        'modules/sunburst'
    ],
    'series.supertrend': [
        'indicators/indicators',
        'indicators/supertrend'
    ],
    'series.tema': [
        'indicators/indicators',
        'indicators/tema'
    ],
    'series.tilemap': [
        'modules/tilemap'
    ],
    'series.timeline': [
        'modules/timeline'
    ],
    'series.treegraph': [
        'modules/treemap',
        'modules/treegraph'
    ],
    'series.treemap': [
        'modules/treemap'
    ],
    'series.trendline': [
        'indicators/indicators',
        'indicators/trendline'
    ],
    'series.trix': [
        'indicators/indicators',
        'indicators/tema'
    ],
    'series.variablepie': [
        'modules/variable-pie'
    ],
    'series.variwide': [
        'modules/variwide'
    ],
    'series.vbp': [
        'indicators/indicators',
        'indicators/volume-by-price'
    ],
    'series.vector': [
        'modules/vector'
    ],
    'series.venn': [
        'modules/venn'
    ],
    'series.vwap': [
        'indicators/indicators',
        'indicators/vwap'
    ],
    'series.waterfall': [
        'highcharts-more'
    ],
    'series.williamsr': [
        'indicators/indicators',
        'indicators/williams-r'
    ],
    'series.windbarb': [
        'modules/windbarb'
    ],
    'series.wma': [
        'indicators/indicators',
        'indicators/wma'
    ],
    'series.wordcloud': [
        'modules/wordcloud'
    ],
    'series.xrange.data.connect': [
        'highcharts-gantt'
    ],
    'series.xrange': [
        'modules/xrange'
    ],
    'series.zigzag': [
        'indicators/indicators',
        'indicators/zigzag'
    ],
    'sonification': [
        'modules/sonification'
    ],
    'xAxis.accessibility': [
        'modules/accessibility'
    ],
    'xAxis.labels.position3d': [
        'highcharts-3d'
    ],
    'xAxis.labels.skew3d': [
        'highcharts-3d'
    ],
    'xAxis.title.position3d': [
        'highcharts-3d'
    ],
    'xAxis.title.skew3d': [
        'highcharts-3d'
    ],
    'yAxis.maxLength': [
        'modules/drag-panes'
    ],
    'yAxis.minLength': [
        'modules/drag-panes'
    ],
    'yAxis.resize': [
        'modules/drag-panes'
    ],
    'yAxis.stackShadow': [
        'modules/pictorial'
    ],
    'yAxis.tooltipValueFormat': [
        'modules/parallel-coordinates'
    ]
};
export default DependencyMapping;
