/**
 * Dependencies for the autoload feature.
 *
 * DO NOT EDIT THIS FILE. This file is generated using the
 * 'gulp dependency-mapping' task.
 */
const DependencyMapping: Record<string, Array<string>> = {
    'accessibility': [
        'modules/accessibility'
    ],
    'annotations.labelOptions.accessibility': [
        'modules/accessibility'
    ],
    'annotations.labelOptions.includeInDataExport': [
        'modules/export-data'
    ],
    'annotations.labels.point': [
        'modules/annotations'
    ],
    'annotations.shapes.point': [
        'modules/annotations'
    ],
    'annotations.type': [
        'modules/annotations-advanced'
    ],
    'annotations.types': [
        'modules/annotations-advanced'
    ],
    'annotations': [
        'modules/annotations'
    ],
    'boost': [
        'modules/boost'
    ],
    'chart.displayErrors': [
        'modules/debugger'
    ],
    'chart.events.afterPrint': [
        'modules/exporting'
    ],
    'chart.events.beforePrint': [
        'modules/exporting'
    ],
    'chart.events.drilldown': [
        'modules/drilldown'
    ],
    'chart.events.drillup': [
        'modules/drilldown'
    ],
    'chart.events.drillupall': [
        'modules/drilldown'
    ],
    'chart.events.exportData': [
        'modules/exporting',
        'modules/export-data'
    ],
    'chart.events.fullscreenClose': [
        'modules/full-screen'
    ],
    'chart.events.fullscreenOpen': [
        'modules/full-screen'
    ],
    'chart.options3d': [
        'highcharts-3d'
    ],
    'chart.parallelAxes': [
        'modules/parallel-coordinates'
    ],
    'chart.parallelCoordinates': [
        'modules/parallel-coordinates'
    ],
    'chart.polar': [
        'highcharts-more'
    ],
    'chart.zoomKey': [
        'modules/draggable-points'
    ],
    'chart.zooming.key': [
        'modules/draggable-points'
    ],
    'chart.zooming.mouseWheel': [
        'modules/mouse-wheel-zoom'
    ],
    'data': [
        'modules/data'
    ],
    'drilldown': [
        'modules/drilldown'
    ],
    'exporting.accessibility': [
        'modules/accessibility'
    ],
    'exporting.csv.annotations': [
        'modules/exporting',
        'modules/export-data',
        'modules/annotations'
    ],
    'exporting.csv': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.error': [
        'modules/exporting',
        'modules/offline-exporting'
    ],
    'exporting.fallbackToExportServer': [
        'modules/exporting',
        'modules/offline-exporting'
    ],
    'exporting.menuItemDefinitions': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.pdfFont': [
        'modules/offline-exporting'
    ],
    'exporting.showExportInProgress': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.showTable': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.tableCaption': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.useMultiLevelHeaders': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting.useRowspanHeaders': [
        'modules/exporting',
        'modules/export-data'
    ],
    'exporting': [
        'modules/exporting'
    ],
    'legend.accessibility': [
        'modules/accessibility'
    ],
    'legend.bubbleLegend': [
        'highcharts-more'
    ],
    'navigation.annotationsOptions': [
        'modules/annotations'
    ],
    'navigation.bindings': [
        'modules/annotations'
    ],
    'navigation': [
        'modules/exporting'
    ],
    'navigator.accessibility': [
        'modules/accessibility'
    ],
    'noData': [
        'modules/no-data-to-display'
    ],
    'pane': [
        'highcharts-more'
    ],
    'series.abands': [
        'stock/indicators/indicators',
        'stock/indicators/acceleration-bands'
    ],
    'series.ad': [
        'stock/indicators/indicators',
        'stock/indicators/accumulation-distribution'
    ],
    'series.ao': [
        'stock/indicators/indicators',
        'stock/indicators/ao'
    ],
    'series.apo': [
        'stock/indicators/indicators',
        'stock/indicators/apo'
    ],
    'series.arcdiagram': [
        'modules/sankey',
        'modules/arc-diagram'
    ],
    'series.arearange': [
        'highcharts-more'
    ],
    'series.areasplinerange': [
        'highcharts-more'
    ],
    'series.aroon': [
        'stock/indicators/indicators',
        'stock/indicators/aroon'
    ],
    'series.aroonoscillator': [
        'stock/indicators/indicators',
        'stock/indicators/aroon',
        'stock/indicators/aroon-oscillator'
    ],
    'series.atr': [
        'stock/indicators/indicators',
        'stock/indicators/atr'
    ],
    'series.bb': [
        'stock/indicators/indicators',
        'stock/indicators/bollinger-bands'
    ],
    'series.bellcurve': [
        'modules/histogram-bellcurve'
    ],
    'series.boxplot': [
        'highcharts-more'
    ],
    'series.bubble': [
        'highcharts-more'
    ],
    'series.bullet': [
        'modules/bullet'
    ],
    'series.cci': [
        'stock/indicators/indicators',
        'stock/indicators/cci'
    ],
    'series.chaikin': [
        'stock/indicators/indicators',
        'stock/indicators/chaikin'
    ],
    'series.cmf': [
        'stock/indicators/indicators',
        'stock/indicators/cmf'
    ],
    'series.cmo': [
        'stock/indicators/indicators',
        'stock/indicators/cmo'
    ],
    'series.columnpyramid': [
        'highcharts-more'
    ],
    'series.columnrange': [
        'highcharts-more'
    ],
    'series.cylinder': [
        'highcharts-3d',
        'modules/cylinder'
    ],
    'series.dema': [
        'stock/indicators/indicators',
        'stock/indicators/dema'
    ],
    'series.dependencywheel': [
        'modules/sankey',
        'modules/dependency-wheel'
    ],
    'series.disparityindex': [
        'stock/indicators/indicators',
        'stock/indicators/disparity-index'
    ],
    'series.dmi': [
        'stock/indicators/indicators',
        'stock/indicators/dmi'
    ],
    'series.dpo': [
        'stock/indicators/indicators',
        'stock/indicators/dpo'
    ],
    'series.dumbbell': [
        'highcharts-more',
        'modules/dumbbell'
    ],
    'series.ema': [
        'stock/indicators/indicators'
    ],
    'series.errorbar': [
        'highcharts-more'
    ],
    'series.funnel': [
        'modules/funnel'
    ],
    'series.funnel3d': [
        'highcharts-3d',
        'modules/cylinder',
        'modules/funnel3d'
    ],
    'series.gantt': [
        'highcharts-gantt'
    ],
    'series.gauge': [
        'highcharts-more'
    ],
    'series.heikinashi': [
        'modules/heikinashi'
    ],
    'series.histogram': [
        'modules/histogram-bellcurve'
    ],
    'series.ikh': [
        'stock/indicators/indicators',
        'stock/indicators/ichimoku-kinko-hyo'
    ],
    'series.item': [
        'modules/item-series'
    ],
    'series.keltnerchannels': [
        'stock/indicators/indicators',
        'stock/indicators/keltner-channels'
    ],
    'series.klinger': [
        'stock/indicators/indicators',
        'stock/indicators/klinger'
    ],
    'series.line.data.description': [
        'modules/accessibility'
    ],
    'series.line.data.dragDrop': [
        'modules/draggable-points'
    ],
    'series.line.data.drilldown': [
        'modules/drilldown'
    ],
    'series.linearregression': [
        'stock/indicators/indicators',
        'stock/indicators/regressions'
    ],
    'series.linearregressionangle': [
        'stock/indicators/indicators',
        'stock/indicators/regressions'
    ],
    'series.linearregressionintercept': [
        'stock/indicators/indicators',
        'stock/indicators/regressions'
    ],
    'series.linearregressionslope': [
        'stock/indicators/indicators',
        'stock/indicators/regressions'
    ],
    'series.lollipop': [
        'highcharts-more',
        'modules/dumbbell',
        'modules/lollipop'
    ],
    'series.macd': [
        'stock/indicators/indicators',
        'stock/indicators/macd'
    ],
    'series.mfi': [
        'stock/indicators/indicators',
        'stock/indicators/mfi'
    ],
    'series.momentum': [
        'stock/indicators/indicators',
        'stock/indicators/momentum'
    ],
    'series.natr': [
        'stock/indicators/indicators',
        'stock/indicators/atr',
        'stock/indicators/natr'
    ],
    'series.networkgraph': [
        'modules/networkgraph'
    ],
    'series.obv': [
        'stock/indicators/indicators',
        'stock/indicators/obv'
    ],
    'series.organization': [
        'modules/sankey',
        'modules/organization'
    ],
    'series.packedbubble': [
        'highcharts-more'
    ],
    'series.pareto': [
        'modules/pareto'
    ],
    'series.pc': [
        'stock/indicators/indicators',
        'stock/indicators/price-channel'
    ],
    'series.pictorial': [
        'modules/pictorial'
    ],
    'series.pivotpoints': [
        'stock/indicators/indicators',
        'stock/indicators/pivot-points'
    ],
    'series.pointandfigure': [
        'modules/pointandfigure'
    ],
    'series.polygon': [
        'highcharts-more'
    ],
    'series.ppo': [
        'stock/indicators/indicators',
        'stock/indicators/ppo'
    ],
    'series.priceenvelopes': [
        'stock/indicators/indicators',
        'stock/indicators/price-envelopes'
    ],
    'series.psar': [
        'stock/indicators/indicators',
        'stock/indicators/psar'
    ],
    'series.pyramid': [
        'modules/funnel'
    ],
    'series.pyramid3d': [
        'highcharts-3d',
        'modules/cylinder',
        'modules/funnel3d',
        'modules/pyramid3d'
    ],
    'series.renko': [
        'modules/renko'
    ],
    'series.roc': [
        'stock/indicators/indicators',
        'stock/indicators/roc'
    ],
    'series.rsi': [
        'stock/indicators/indicators',
        'stock/indicators/rsi'
    ],
    'series.sankey': [
        'modules/sankey'
    ],
    'series.scatter3d': [
        'highcharts-3d'
    ],
    'series.slowstochastic': [
        'stock/indicators/indicators',
        'stock/indicators/stochastic',
        'stock/indicators/slow-stochastic'
    ],
    'series.sma': [
        'stock/indicators/indicators'
    ],
    'series.solidgauge': [
        'highcharts-more',
        'modules/solid-gauge'
    ],
    'series.stochastic': [
        'stock/indicators/indicators',
        'stock/indicators/stochastic'
    ],
    'series.streamgraph': [
        'modules/streamgraph'
    ],
    'series.sunburst': [
        'modules/sunburst'
    ],
    'series.supertrend': [
        'stock/indicators/indicators',
        'stock/indicators/supertrend'
    ],
    'series.tema': [
        'stock/indicators/indicators',
        'stock/indicators/tema'
    ],
    'series.tilemap': [
        'modules/tilemap'
    ],
    'series.timeline': [
        'modules/timeline'
    ],
    'series.treegraph': [
        'modules/treemap',
        'modules/treegraph'
    ],
    'series.treemap': [
        'modules/treemap'
    ],
    'series.trendline': [
        'stock/indicators/indicators',
        'stock/indicators/trendline'
    ],
    'series.trix': [
        'stock/indicators/indicators',
        'stock/indicators/tema',
        'stock/indicators/trix'
    ],
    'series.variablepie': [
        'modules/variable-pie'
    ],
    'series.variwide': [
        'modules/variwide'
    ],
    'series.vbp': [
        'stock/indicators/indicators',
        'stock/indicators/volume-by-price'
    ],
    'series.vector': [
        'modules/vector'
    ],
    'series.venn': [
        'modules/venn'
    ],
    'series.vwap': [
        'stock/indicators/indicators',
        'stock/indicators/vwap'
    ],
    'series.waterfall': [
        'highcharts-more'
    ],
    'series.williamsr': [
        'stock/indicators/indicators',
        'stock/indicators/williams-r'
    ],
    'series.windbarb': [
        'modules/windbarb'
    ],
    'series.wma': [
        'stock/indicators/indicators',
        'stock/indicators/wma'
    ],
    'series.wordcloud': [
        'modules/wordcloud'
    ],
    'series.xrange.data.connect': [
        'highcharts-gantt'
    ],
    'series.xrange': [
        'modules/xrange'
    ],
    'series.zigzag': [
        'stock/indicators/indicators',
        'stock/indicators/zigzag'
    ],
    'sonification': [
        'modules/sonification'
    ],
    'stockTools': [
        'stock/modules/stock-tools'
    ],
    'xAxis.accessibility': [
        'modules/accessibility'
    ],
    'xAxis.labels.position3d': [
        'highcharts-3d'
    ],
    'xAxis.labels.skew3d': [
        'highcharts-3d'
    ],
    'xAxis.title.position3d': [
        'highcharts-3d'
    ],
    'xAxis.title.skew3d': [
        'highcharts-3d'
    ],
    'yAxis.maxLength': [
        'modules/drag-panes'
    ],
    'yAxis.minLength': [
        'modules/drag-panes'
    ],
    'yAxis.resize': [
        'modules/drag-panes'
    ],
    'yAxis.stackShadow': [
        'modules/pictorial'
    ],
    'yAxis.tooltipValueFormat': [
        'modules/parallel-coordinates'
    ],
    'series.arearange.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'series.arearange.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'series.boxplot.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'series.boxplot.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'series.boxplot.dragDrop.draggableQ1': [
        'modules/draggable-points'
    ],
    'series.boxplot.dragDrop.draggableQ3': [
        'modules/draggable-points'
    ],
    'series.bullet.dragDrop.draggableTarget': [
        'modules/draggable-points'
    ],
    'series.column.depth': [
        'highcharts-3d'
    ],
    'series.column.edgeColor': [
        'highcharts-3d'
    ],
    'series.column.edgeWidth': [
        'highcharts-3d'
    ],
    'series.column.groupZPadding': [
        'highcharts-3d'
    ],
    'series.columnrange.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'series.columnrange.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'series.flowmap': [
        'modules/flowmap'
    ],
    'series.gantt.dragDrop.draggableEnd': [
        'modules/draggable-points'
    ],
    'series.gantt.dragDrop.draggableStart': [
        'modules/draggable-points'
    ],
    'series.geoheatmap': [
        'modules/geoheatmap'
    ],
    'series.hollowcandlestick': [
        'modules/hollowcandlestick'
    ],
    'series.ohlc.dragDrop.draggableClose': [
        'modules/draggable-points'
    ],
    'series.ohlc.dragDrop.draggableHigh': [
        'modules/draggable-points'
    ],
    'series.ohlc.dragDrop.draggableLow': [
        'modules/draggable-points'
    ],
    'series.ohlc.dragDrop.draggableOpen': [
        'modules/draggable-points'
    ],
    'series.pie.depth': [
        'highcharts-3d'
    ],
    'series.series.accessibility': [
        'modules/accessibility'
    ],
    'series.series.boostBlending': [
        'modules/boost'
    ],
    'series.series.boostThreshold': [
        'modules/boost'
    ],
    'series.series.dataGrouping': [
        'modules/stock'
    ],
    'series.series.description': [
        'modules/accessibility'
    ],
    'series.series.dragDrop': [
        'modules/draggable-points'
    ],
    'series.series.gapSize': [
        'modules/broken-axis'
    ],
    'series.series.gapUnit': [
        'modules/broken-axis'
    ],
    'series.series.includeInDataExport': [
        'modules/exporting',
        'modules/export-data'
    ],
    'series.series.label': [
        'modules/series-label'
    ],
    'series.series.lastPrice': [
        'modules/price-indicator'
    ],
    'series.series.lastVisiblePrice': [
        'modules/price-indicator'
    ],
    'series.series.onPoint': [
        'modules/series-on-point'
    ],
    'series.series.point.events.drag': [
        'modules/draggable-points'
    ],
    'series.series.point.events.dragStart': [
        'modules/draggable-points'
    ],
    'series.series.point.events.drop': [
        'modules/draggable-points'
    ],
    'series.series.sonification': [
        'modules/sonification'
    ],
    'series.tiledwebmap': [
        'modules/tiledwebmap'
    ],
    'series.xrange.dragDrop.draggableX1': [
        'modules/draggable-points'
    ],
    'series.xrange.dragDrop.draggableX2': [
        'modules/draggable-points'
    ]
};
export default DependencyMapping;
