import Highcharts './highcharts.js';
import '../parts/OrdinalAxis.js';
import '../modules/broken-axis.src.js';
import '../parts/DataGrouping.js';
import '../parts/OHLCSeries.js';
import '../parts/CandlestickSeries.js';
import '../parts/FlagsSeries.js';
import '../parts/Scroller.js';
import '../parts/RangeSelector.js';
import '../parts/StockNavigation.js';
import '../parts/StockChart.js';
export default Highcharts; 