/* *
 *
 *  Grid deprecated runtime metadata
 *
 *  WARNING: This file is generated by `npx gulp grid/deprecated-options`.
 *  Do not edit this file manually.
 *
 * */

'use strict';

interface DeprecatedOptionPropertySegment {
    kind: 'property';
    name: string;
}

interface DeprecatedOptionDiscriminatorSegment {
    allowUndefined?: boolean;
    kind: 'discriminator';
    name: string;
    value: string;
}

type DeprecatedOptionMatchSegment =
    DeprecatedOptionDiscriminatorSegment |
    DeprecatedOptionPropertySegment;

interface DeprecatedOptionMetadata {
    docsPath: string;
    runtimePath: string;
    segments: Array<DeprecatedOptionMatchSegment>;
    text: string;
}

const deprecatedOptionsMetadata: Array<DeprecatedOptionMetadata> = [
    {
        'docsPath': 'dataTable',
        'runtimePath': 'dataTable',
        'segments': [
            {
                'kind': 'property',
                'name': 'dataTable'
            }
        ],
        'text': '2.3.0'
    },
    {
        'docsPath': 'lang.pinRowBottom',
        'runtimePath': 'lang.pinRowBottom',
        'segments': [
            {
                'kind': 'property',
                'name': 'lang'
            },
            {
                'kind': 'property',
                'name': 'pinRowBottom'
            }
        ],
        'text': 'Use `lang.rowPinning.pinRowBottom` instead.'
    },
    {
        'docsPath': 'lang.pinRowTop',
        'runtimePath': 'lang.pinRowTop',
        'segments': [
            {
                'kind': 'property',
                'name': 'lang'
            },
            {
                'kind': 'property',
                'name': 'pinRowTop'
            }
        ],
        'text': 'Use `lang.rowPinning.pinRowTop` instead.'
    },
    {
        'docsPath': 'lang.unpinRow',
        'runtimePath': 'lang.unpinRow',
        'segments': [
            {
                'kind': 'property',
                'name': 'lang'
            },
            {
                'kind': 'property',
                'name': 'unpinRow'
            }
        ],
        'text': 'Use `lang.rowPinning.unpinRow` instead.'
    }
];

export type { DeprecatedOptionMatchSegment, DeprecatedOptionMetadata };
export { deprecatedOptionsMetadata };
