/* *
 *
 *  Creating Grid deprecated runtime metadata from TypeScript doclets.
 *
 *  (c) Highsoft AS
 * 
 *  Authors:
 *  - Dawid Dragula
 * 
 * */


/* *
 *
 *  Imports
 *
 * */


import FS from 'node:fs';
import * as Path from 'node:path';

import LogLib from '../libs/log.js';
import Yargs from 'yargs';

import { buildGridOptionsTree } from './grid-options';


/* *
 *
 *  Declarations
 *
 * */

interface Args {
    debug?: boolean;
    output?: string;
    source?: string;
}

interface OptionNode {
    children?: Record<string, OptionNode>;
    doclet?: {
        deprecated?: unknown;
    };
}


/* *
 *
 *  Constants
 *
 * */

const DEFAULT_OUTPUT = Path.resolve(
    'ts/Grid/Core/DeprecatedOptionsMetadata.ts'
);


/* *
 *
 *  Functions
 *
 * */

function collectDeprecatedOptions(
    tree: Record<string, OptionNode>
): Record<string, string> {
    const deprecatedOptions: Record<string, string> = {};

    const visit = (
        nodes: Record<string, OptionNode>,
        parentPath = ''
    ): void => {
        const nodeNames = Object.keys(nodes)
            .filter((name): boolean => name !== '_meta')
            .sort();

        for (const nodeName of nodeNames) {
            const node = nodes[nodeName];
            const path = parentPath ? `${parentPath}.${nodeName}` : nodeName;
            const deprecatedText = normalizeDocletText(
                node.doclet?.deprecated
            );

            if (typeof deprecatedText !== 'undefined') {
                deprecatedOptions[path] = deprecatedText;
            }

            if (node.children) {
                visit(node.children, path);
            }
        }
    };

    visit(tree);

    return deprecatedOptions;
}

function normalizeDocletText(value: unknown): string | undefined {
    const normalizeText = (text: string): string => (
        text.replace(
            /\{@link\s+([^}\s|]+)(?:\s*\|\s*([^}]+)|\s+([^}]+))?\}/gu,
            (
                _match,
                target: string,
                pipeLabel?: string,
                spaceLabel?: string
            ) => (pipeLabel || spaceLabel || target).trim()
        ).trim()
    );

    if (Array.isArray(value)) {
        const text = value
            .map((item): string => `${item}`.trim())
            .filter(Boolean)
            .join('\n\n')
            .trim();

        return normalizeText(text) || '';
    }

    if (typeof value === 'string') {
        return normalizeText(value);
    }

    if (typeof value === 'boolean') {
        return '';
    }

    return void 0;
}

function stringifySingleQuoted(value: string): string {
    return `'${value
        .replace(/\\/gu, '\\\\')
        .replace(/'/gu, '\\\'')}'`;
}

function serializeLiteral(
    value: Record<string, unknown> | string,
    indentLevel = 0
): string {
    if (typeof value === 'string') {
        return stringifySingleQuoted(value);
    }

    const indent = '    '.repeat(indentLevel);
    const childIndent = '    '.repeat(indentLevel + 1);
    const entries = Object.entries(value);

    if (!entries.length) {
        return '{}';
    }

    const serializedEntries = entries.map(
        ([key, entryValue]): string => `${childIndent}${stringifySingleQuoted(
            key
        )}: ${serializeLiteral(
            entryValue as Record<string, unknown> | string,
            indentLevel + 1
        )}`
    );

    return `{\n${serializedEntries.join(',\n')}\n${indent}}`;
}

function renderMetadataModule(
    deprecatedOptions: Record<string, string>
): string {
    const normalizedEntries = Object.entries(deprecatedOptions)
        .sort(([leftPath], [rightPath]): number => (
            leftPath.localeCompare(rightPath)
        ))
        .map(([path, text]) => [path, text]);
    const serialized = serializeLiteral(Object.fromEntries(normalizedEntries));

    return `/* *
 *
 *  Grid deprecated runtime metadata
 *
 *  WARNING: This file is generated by \`npx gulp grid/deprecated-options\`.
 *  Do not edit this file manually.
 *
 * */

'use strict';

const deprecatedOptionsMetadata: Record<string, string> = ${serialized};

export { deprecatedOptionsMetadata };
`;
}

async function main(): Promise<void> {
    const args = Yargs.parseSync(process.argv) as Args;
    const outputPath = args.output || DEFAULT_OUTPUT;
    const tree = await buildGridOptionsTree(args);
    const deprecatedOptions = collectDeprecatedOptions(tree);

    FS.mkdirSync(Path.dirname(outputPath), { recursive: true });
    FS.writeFileSync(
        outputPath,
        renderMetadataModule(deprecatedOptions),
        'utf8'
    );

    LogLib.success(
        'Saved',
        outputPath,
        `(${Object.keys(deprecatedOptions).length} deprecated options).`
    );
}


/* *
 *
 *  Runtime
 *
 * */


void main();
