import { test, expect } from '~/fixtures.ts';
import type { Page } from '@playwright/test';

async function getViewportColumnIds(page: Page): Promise<string[]> {
    return page.evaluate(() => {
        const grid = (window as any).Grid.grids[0];
        return grid.viewport.columns.map(
            (column: { id: string }) => column.id
        );
    });
}

test.describe('Autogenerated columns with configured unbound column', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('/grid-lite/e2e/unbound-in-autogen-column', { waitUntil: 'networkidle' });
    });

    test('Should keep auto columns, append configured unbound column and skip disabled auto column', async ({ page }) => {
        const columnIds = await getViewportColumnIds(page);
        expect(columnIds).toEqual(['product', 'price', 'unbound']);

        await expect(page.locator('.hcg-header-cell[data-column-id="weight"]')).toHaveCount(0);
        await expect(page.locator('tbody tr')).toHaveCount(4);
        await expect(page.locator('tbody td[data-column-id="unbound"]')).toHaveCount(4);

        const values = (
            await page.locator('tbody td[data-column-id="unbound"]').allTextContents()
        ).map((value) => value.trim());

        // `valueGetter` check: 4 unique values
        expect(values.every((value) => value.length > 0)).toBe(true);
        expect(new Set(values).size).toBe(4);
    });
});

test.describe('Autogenerate columns disabled', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('/grid-lite/e2e/autogenerate-columns-disabled', { waitUntil: 'networkidle' });
    });

    test('Should render only configured columns', async ({ page }) => {
        const columnIds = await getViewportColumnIds(page);
        expect(columnIds).toEqual(['sum', 'sales', 'price', 'product']);

        await expect(page.locator('.hcg-header-cell[data-column-id="ignoredByConfig"]')).toHaveCount(0);
        await expect(page.locator('.hcg-header-cell[data-column-id="revenue"]')).toHaveCount(0);
        await expect(page.locator('tbody tr')).toHaveCount(4);
    });

    test('Should keep configured columns after data update', async ({ page }) => {
        await page.locator('#useLargeDataset').check();
        await expect(
            page.locator('tbody td[data-column-id="product"]').first()
        ).toContainText('Product 1');

        expect(await getViewportColumnIds(page)).toEqual(['sum', 'sales', 'price', 'product']);
        await expect(page.locator('.hcg-header-cell[data-column-id="ignoredByConfig"]')).toHaveCount(0);

        await page.locator('#useLargeDataset').uncheck();

        await expect(
            page.locator('tbody td[data-column-id="product"]').first()
        ).toContainText('Apples');
        expect(await getViewportColumnIds(page)).toEqual(['sum', 'sales', 'price', 'product']);
    });
});
