
 Data plugin for Highcharts

 (c) 2012-2013 Torstein HÞnsi
 Last revision 2012-11-27

 License www.highcharts.comlicense

(function(f){var k=f.each,n=function(a){this.init(a)};f.extend(n.prototype,{initfunction(a){this.options=a;this.columns=a.columnsthis.rowsToColumns(a.rows)[];this.columns.lengththis.dataFound()(this.parseCSV(),this.parseTable(),this.parseGoogleSpreadsheet())},dataFoundfunction(){this.parseTypes();this.findHeaderRow();this.parsed();this.complete()},parseCSVfunction(){var a=this,b=this.options,c=b.csv,d=this.columns,e=b.startRow0,g=b.endRowNumber.MAX_VALUE,h=b.startColumn0,l=b.endColumn
Number.MAX_VALUE,q=0;c&&(c=c.replace(rng,n).replace(rg,n).split(b.lineDelimitern),k(c,function(c,m){var o=a.trim(c),f=o.indexOf(#)===0;m=e&&m=g&&!f&&o!==&&(o=c.split(b.itemDelimiter,),k(o,function(b,a){a=h&&a=l&&(d[a-h](d[a-h]=[]),d[a-h][q]=b)}),q+=1)}),this.dataFound())},parseTablefunction(){var a=this.options,b=a.table,c=this.columns,d=a.startRow0,e=a.endRowNumber.MAX_VALUE,g=a.startColumn0,h=a.endColumnNumber.MAX_VALUE,l;b&&(typeof b===string&&(b=document.getElementById(b)),
k(b.getElementsByTagName(tr),function(a,b){l=0;b=d&&b=e&&k(a.childNodes,function(a){if((a.tagName===TDa.tagName===TH)&&l=g&&l=h)c[l](c[l]=[]),c[l][b-d]=a.innerHTML,l+=1})}),this.dataFound())},parseGoogleSpreadsheetfunction(){var a=this,b=this.options,c=b.googleSpreadsheetKey,d=this.columns,e=b.startRow0,g=b.endRowNumber.MAX_VALUE,h=b.startColumn0,l=b.endColumnNumber.MAX_VALUE,f,j;c&&jQuery.getJSON(httpsspreadsheets.google.comfeedscells+c++(b.googleSpreadsheetWorksheet
od6)+publicvaluesalt=json-in-script&callback=,function(b){var b=b.feed.entry,c,k=b.length,n=0,p=0,i;for(i=0;ik;i++)c=b[i],n=Math.max(n,c.gs$cell.col),p=Math.max(p,c.gs$cell.row);for(i=0;in;i++)if(i=h&&i=l)d[i-h]=[],d[i-h].length=Math.min(p,g-e);for(i=0;ik;i++)if(c=b[i],f=c.gs$cell.row-1,j=c.gs$cell.col-1,j=h&&j=l&&f=e&&f=g)d[j-h][f-e]=c.content.$t;a.dataFound()})},findHeaderRowfunction(){k(this.columns,function(){});this.headerRow=0},trimfunction(a){return typeof a===stringa.replace(^s+s+$g,
)a},parseTypesfunction(){for(var a=this.columns,b=a.length,c,d,e,g;b--;)for(c=a[b].length;c--;)d=a[b][c],e=parseFloat(d),g=this.trim(d),g==e(a[b][c]=e,e31536E6a[b].isDatetime=!0a[b].isNumeric=!0)(d=this.parseDate(d),b===0&&typeof d===number&&!isNaN(d)(a[b][c]=d,a[b].isDatetime=!0)a[b][c]=g===nullg)},dateFormats{YYYY-mm-dd{regex^([0-9]{4})-([0-9]{2})-([0-9]{2})$,parserfunction(a){return Date.UTC(+a[1],a[2]-1,+a[3])}}},parseDatefunction(a){var b=this.options.parseDate,c,d,
e;b&&(c=b(a));if(typeof a===string)for(d in this.dateFormats)b=this.dateFormats[d],(e=a.match(b.regex))&&(c=b.parser(e));return c},rowsToColumnsfunction(a){var b,c,d,e,g;if(a){g=[];c=a.length;for(b=0;bc;b++){e=a[b].length;for(d=0;de;d++)g[d](g[d]=[]),g[d][b]=a[b][d]}}return g},parsedfunction(){this.options.parsed&&this.options.parsed.call(this,this.columns)},completefunction(){var a=this.columns,b,c,d,e,g=this.options,h,f,k,j,m;if(g.complete){a.length1&&(d=a.shift(),this.headerRow===0&&
d.shift(),(b=d.isNumericd.isDatetime)(c=d),d.isDatetime&&(e=datetime));h=[];for(j=0;ja.length;j++){this.headerRow===0&&(k=a[j].shift());f=[];for(m=0;ma[j].length;m++)f[m]=a[j][m]!==void 0b[d[m],a[j][m]]a[j][m]null;h[j]={namek,dataf}}g.complete({xAxis{categoriesc,typee},seriesh})}}});f.Data=n;f.data=function(a){return new n(a)};f.wrap(f.Chart.prototype,init,function(a,b,c){var d=this;b&&b.dataf.data(f.extend(b.data,{completefunction(e){b.series&&k(b.series,function(a,c){b.series[c]=
f.merge(a,e.series[c])});b=f.merge(e,b);a.call(d,b,c)}}))a.call(d,b,c)})})(Highcharts);