#!/usr/bin/env node
const { execSync } = require('node:child_process');

if (process.argv.includes('-h') || process.argv.includes('--help')) {
    console.log([
        'affected-product [PRODUCT_FOLDERS]',
        'Tests whether a product folder is affected by new commits.',
        '',
        '  [PRODUCT_FOLDERS] - Folder in ./ts',
        '',
        'Exit with code 0, if product folders are affected.',
        'Exit with code 1, if product folders are not affected.'
    ].join('\n'));
    process.exit(1);
}

const affectedFolders = execSync('git diff HEAD^ HEAD --name-only --diff-filter=ACM')
        .toString()
        .split(/\s/gu)
        .filter(path => !!path)
        .map(path => path.split(/\//gu)[1]),
    testFolders = process.argv.filter(folder => folder[0] !== '/');

for (const folder of testFolders) {
    if (affectedFolders.includes(folder)) {
        console.log(`${folder} affected`);
        process.exit(0);
    }
}

process.exit(1);
