// DO NOT EDIT, file is generated by the prepare-react-samples gulp task
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Chart, Series, Title, getHighcharts } from '@highcharts/react/index';
import { Tooltip, PlotOptions, Legend, Subtitle, Credits, YAxis, XAxis } from '@highcharts/react/options';
import { Data } from '@highcharts/react/options/Data';
import { Exporting } from '@highcharts/react/options/Exporting';
import { Accessibility } from '@highcharts/react/options/Accessibility';
export default function ChartComponent() {
    return /*#__PURE__*/ React.createElement("div", null, /*#__PURE__*/ React.createElement(Chart, null, /*#__PURE__*/ React.createElement(Title, null, "Fruit collection"), /*#__PURE__*/ React.createElement(Subtitle, null, "Comparing apples, pears, and oranges"), /*#__PURE__*/ React.createElement(Credits, {
        href: "https://www.highcharts.com"
    }, "Credit text"), /*#__PURE__*/ React.createElement(Legend, null, '{name}\'s fruits'), /*#__PURE__*/ React.createElement(PlotOptions, {
        series: {
            animation: false
        }
    }), /*#__PURE__*/ React.createElement(Tooltip, {
        useHTML: true
    }, /*#__PURE__*/ React.createElement("div", {
        "data-hc-option": "headerFormat"
    }, /*#__PURE__*/ React.createElement("strong", {
        style: {
            color: 'dimgray'
        }
    }, 'Series {series.name}')), /*#__PURE__*/ React.createElement("div", {
        "data-hc-option": "pointFormat"
    }, 'X: {point.x}, Y: {point.y}'), /*#__PURE__*/ React.createElement("div", {
        "data-hc-option": "footerFormat"
    }, /*#__PURE__*/ React.createElement("em", null, "Footer text"))), /*#__PURE__*/ React.createElement(XAxis, {
        gridLineWidth: 2
    }, "Fruit"), /*#__PURE__*/ React.createElement(YAxis, {
        gridLineWidth: 2,
        gridLineDashStyle: 'Dash'
    }, "Number of fruits"), /*#__PURE__*/ React.createElement(Data, {
        columns: [
            [
                null,
                'Apples',
                'Pears',
                'Oranges'
            ],
            [
                'Ola',
                1,
                4,
                3
            ],
            [
                'Kari',
                5,
                4,
                2
            ]
        ]
    }), /*#__PURE__*/ React.createElement(Series, {
        type: 'column'
    }), " ", /*#__PURE__*/ React.createElement(Series, {
        type: 'column'
    }), " ", /*#__PURE__*/ React.createElement(Series, {
        type: 'column',
        options: {
            name: 'Espen'
        },
        data: [
            [
                'Apples',
                4
            ]
        ]
    }), /*#__PURE__*/ React.createElement(Exporting, null), /*#__PURE__*/ React.createElement(Accessibility, null)));
}
ReactDOM.createRoot(document.querySelector('#container'))?.render(/*#__PURE__*/ React.createElement(ChartComponent, null));
