# This is a basic workflow to help you get started with Actions

name: Firefox CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
    paths:
      - 'css/**'
      - 'samples/**'
      - 'test/**'
      - 'ts/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:

  ### HEADLESS ###
  test_headless:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-geckodriver@latest
      - name: Setup Display
        run: sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Install Dependencies
        run: npm i
      # tasks
      - name: Build Highcharts
        run: npx gulp scripts
      - name: Build Dashboards
        run: npx gulp dashboards/scripts
      - name: Check Firefox
        run: |
          firefox --version
          whereis firefox
      - name: Run Firefox Tests (Firefox)
        run: |
          export DISPLAY=:99
          npx gulp test --single-run --splitbrowsers Firefox

  ### BROWSERSTACK ###
  test_browserstack:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: browserstack
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install Dependencies
        run: npm i
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USER }}
          access-key: ${{ secrets.BROWSERSTACK_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
      - name: 'BrowserStackLocal Setup'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-identifier: random
      # tasks
      - name: Build Highcharts
        run: npx gulp scripts
      - name: Run Browserstack Tests (Firefox)
        run: npx gulp test --single-run --splitbrowsers Mac.Firefox
      # clean up
      - name: 'BrowserStackLocal Stop'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop
