name: Grid Lighthouse tests
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/grid-lighthouse-test.yml'
      - 'css/grid*'
      - 'samples/grid-lite/**'
      - 'samples/grid-pro/**'
      - 'test/cypress/grid/performance/**'
      - 'ts/Grid/**'
      - 'ts/Data/**'

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cypress_lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          path: highcharts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: highcharts/package-lock.json

      - name: Install Highcharts dependencies
        run: |
          cd highcharts
          npm ci

      - name: Build Highcharts
        run: |
          cd highcharts
          npx gulp scripts

      - name: Build Grid
        run: |
          cd highcharts
          npx gulp scripts --product Grid

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          repository: highcharts/highcharts-utils
          path: utils
          fetch-depth: 1

      - name: Install Highcharts Utils
        run: |
          cd utils
          npm i

      # DEBUG: Find the lighthouse config file
      - name: Debug - Find lighthouse config file location
        run: |
          echo "=== Current directory ==="
          pwd
          echo ""
          echo "=== Searching for lighthouse.config.mjs everywhere ==="
          find . -name "lighthouse.config.mjs" -type f 2>/dev/null || echo "No lighthouse.config.mjs found"
          echo ""
          echo "=== Searching for any lighthouse config files ==="
          find . -name "*lighthouse*.config.*" -type f 2>/dev/null || echo "No lighthouse config files found"
          echo ""
          echo "=== Searching for cypress.config files ==="
          find . -name "cypress.config.*" -type f 2>/dev/null || echo "No cypress.config files found"
          echo ""
          echo "=== Contents of highcharts/test/cypress/ ==="
          ls -laR highcharts/test/cypress/ 2>/dev/null || echo "Directory does not exist"
          echo ""
          echo "=== All .mjs files in test directory ==="
          find highcharts/test -name "*.mjs" -type f 2>/dev/null || echo "No .mjs files found"

      - name: Run cypress via action
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: node ../utils/server --localOnly
          wait-on: 'http://localhost:3031/grid-lite.js'
          env: type=base
          working-directory: highcharts
          command: npx cypress run --config-file test/cypress/grid/lighthouse.config.mjs --browser chrome
          install: false

      - name: Stop server
        run: kill $(lsof -t -i:3030)

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: highcharts
          clean: false # do not remove files from previous run

      - name: Install Highcharts dependencies
        run: |
          cd highcharts
          npm ci

      - name: Build Highcharts
        run: |
          cd highcharts
          npx gulp scripts

      - name: Build Grid
        run: |
          cd highcharts
          npx gulp scripts --product Grid

      # DEBUG: Find the lighthouse config file again
      - name: Debug - Find lighthouse config file location (current branch)
        run: |
          echo "=== Current directory ==="
          pwd
          echo ""
          echo "=== Searching for lighthouse.config.mjs everywhere ==="
          find . -name "lighthouse.config.mjs" -type f 2>/dev/null || echo "No lighthouse.config.mjs found"
          echo ""
          echo "=== Searching for any lighthouse config files ==="
          find . -name "*lighthouse*.config.*" -type f 2>/dev/null || echo "No lighthouse config files found"
          echo ""
          echo "=== Searching for cypress.config files ==="
          find . -name "cypress.config.*" -type f 2>/dev/null || echo "No cypress.config files found"
          echo ""
          echo "=== Contents of highcharts/test/cypress/ ==="
          ls -laR highcharts/test/cypress/ 2>/dev/null || echo "Directory does not exist"
          echo ""
          echo "=== All .mjs files in test directory ==="
          find highcharts/test -name "*.mjs" -type f 2>/dev/null || echo "No .mjs files found"

      - name: Run cypress via action
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: node ../utils/server --localOnly
          wait-on: 'http://localhost:3031/grid-lite.js'
          env: type=actual
          working-directory: highcharts
          command: npx cypress run --config-file test/cypress/grid/lighthouse.config.mjs --browser chrome
          install: false

      # DEBUG: List tmp directory contents
      - name: Debug - List tmp directory structure
        if: ${{ always() }}
        run: |
          echo "=== Listing highcharts/tmp directory ==="
          ls -la highcharts/tmp/ || echo "tmp directory does not exist"
          echo ""
          echo "=== Tree view of tmp directory ==="
          tree highcharts/tmp/ || find highcharts/tmp/ -type f || echo "No files found in tmp"
          echo ""
          echo "=== Checking for lighthouseReports ==="
          ls -la highcharts/tmp/lighthouseReports/ || echo "lighthouseReports directory does not exist"

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tmp-files
          path: |
            highcharts/tmp

      # DEBUG: Check if lighthouseCompare.mjs exists and is executable
      - name: Debug - Check lighthouseCompare.mjs
        if: ${{ always() }}
        run: |
          echo "=== Checking lighthouseCompare.mjs ==="
          ls -la highcharts/test/cypress/lighthouseCompare.mjs || echo "lighthouseCompare.mjs not found"
          echo ""
          echo "=== Current working directory ==="
          pwd
          echo ""
          echo "=== Directory structure ==="
          ls -la highcharts/test/cypress/

      - name: Write markdown to file
        if: ${{ always() }}
        run: |
          echo "=== Running lighthouseCompare.mjs ==="
          node highcharts/test/cypress/lighthouseCompare.mjs --reportsDir ./highcharts/tmp/lighthouseReports > ./highcharts/tmp/lighthousetable.md
          echo "=== Script completed ==="

      # DEBUG: Verify markdown file was created
      - name: Debug - Check if markdown file exists
        if: ${{ always() }}
        run: |
          echo "=== Checking for lighthousetable.md ==="
          ls -la highcharts/tmp/lighthousetable.md || echo "lighthousetable.md was NOT created"
          echo ""
          if [ -f highcharts/tmp/lighthousetable.md ]; then
            echo "=== Content of lighthousetable.md ==="
            cat highcharts/tmp/lighthousetable.md
          else
            echo "File does not exist, cannot display content"
          fi

      - name: Add to summary
        if: ${{ always() }}
        run: |
          echo "## Lighthouse metrics" >> $GITHUB_STEP_SUMMARY
          if [ -f highcharts/tmp/lighthousetable.md ]; then
            cat highcharts/tmp/lighthousetable.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No lighthouse table file found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        if: ${{ always() }}
        with:
          github-token: ${{secrets.PR_COMMENT_TOKEN}}
          script: |
            const { createOrUpdateComment } = require('./highcharts/.github/scripts/commentOnPR');
            const { readFileSync, existsSync } = require('node:fs');

            const filePath = './highcharts/tmp/lighthousetable.md';
            let markdown = 'No table to show - file was not generated';

            if (existsSync(filePath)) {
              markdown = readFileSync(filePath, 'utf8');
            } else {
              console.log('Warning: lighthousetable.md does not exist at:', filePath);
            }

            await createOrUpdateComment(github, context, 'Lighthouse report', markdown);