name: Playwright Browserstack Tests

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test_playwright_browserstack:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: browserstack
    name: Playwright

    steps:
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_KEY }}
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm ci
        npm i https://github.com/browserstack/node-js-playwright-browserstack.git

    - name: Build Highcharts
      run: npx gulp scripts

    - name: Checkout utils
      uses: actions/checkout@v4
      with:
        repository: highcharts/highcharts-utils
        path: utils
        fetch-depth: 1

    - name: Install Highcharts Utils
      run: |
        cd utils
        npm i

    - name: Run utils
      run: |
        node utils/server --localOnly &

    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_KEY }}

    - name: 'BrowserStackLocal Setup'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: start
        local-identifier: 'abc123'

    - name: Run Playwright tests
      env:
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      run: |
        npx browserstack-node-sdk playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: 'BrowserStackLocal Stop'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: stop
