name: Post-release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Whether to update the nightly branch on highcharts-dist'
        required: false
        default: true
        type: boolean

permissions:
   contents: read # to fetch code (actions/checkout)

jobs:
  generate_release_reference_images:
    runs-on: ubuntu-latest
    env:
      BROWSER_COUNT: 2
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: echo ${{github.ref_name}}

      - run: npm ci
      - run: npx gulp scripts

      - run: |
          npx karma start test/karma-conf.js \
            --tests highcharts/*/* \
            --reference --browsercount "${BROWSER_COUNT}" \
            --no-fail-on-empty-test-suite
          npx karma start test/karma-conf.js \
            --tests stock/*/* \
            --reference --browsercount "${BROWSER_COUNT}" \
            --no-fail-on-empty-test-suite
          npx karma start test/karma-conf.js \
            --tests maps/*/* \
            --reference --browsercount "${BROWSER_COUNT}" \
            --no-fail-on-empty-test-suite
          npx karma start test/karma-conf.js \
            --tests gantt/*/* \
            --reference --browsercount "${BROWSER_COUNT}" \
            --no-fail-on-empty-test-suite


      - name: Publish release reference images
        if: ${{ github.event_name == 'push' || inputs.dryrun == false }}
        env:
          VISUAL_REVIEW_API_KEY: ${{secrets.VISUAL_REVIEW_INGESTION_API_KEY}}
        run: npx gulp update-nightly-testresults --tag "${{github.ref_name}}"



